# Generated by Django 5.2.6 on 2025-12-29 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_options_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'رمز الدعوة', 'verbose_name_plural': 'رموز الدعوة'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'إعداد النظام', 'verbose_name_plural': 'إعدادات النظام'},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='used_by',
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='uses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='InvitationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.invitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_code_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استخدام رمز دعوة',
                'verbose_name_plural': 'استخدامات رموز الدعوة',
                'ordering': ['-used_at'],
                'unique_together': {('invitation', 'user')},
            },
        ),
    ]
